sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t manojnav/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true manojnav/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-406944485982"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY